name: authentication
description: A comprehensive package that manages user authentication, including login, signup, password recovery, and session handling, with support for multiple authentication providers.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  app_ui:
    path: ../../app_ui
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  form_field:
    path: ../../form_field
  fpdart: ^1.1.0
  shared:
    path: ../../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
