name: app_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none
environment:
  sdk: ^3.5.0
dependencies:
  bloc: ^8.1.4
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter


dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
